### ISSUE TITLE
Plugin not work with redmine 3.x

### ISSUE THREAD

**Issue by shachneff** [SteveSimpson/redmine_ssl_auth#1]
Plugin not work with redmine 3.x 
Please help!

**Comment by SteveSimpson** [comment]
We are finally looking at upgrading to 3.x so I will be upgrading this plugin. - I didn't have a testbed and time to set that up.

**Comment by SteveSimpson** [comment]
This has been updated and is now working with 3.x (as far as I know). I have tested current release with 2.6.x and 3.3.0.
